version: "3"

services:
  mysqldb:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    ports:
     - 3306:336
    environment:
     - MYSQL_ROOT_PASSWORD=pass
     - MYSQL_DATABASE=achatdb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=pass


  spring_app:
    image: issamdziri97/achat
    container_name: achatspring
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
     - 8089:8089
    depends_on:
     - mysqldb