version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    user: root
    restart: always
    ports:
      - 3306:3306
    environment:

       MYSQL_DATABASE: achat-db
       MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: issamdziri97/achat
    ports:
      - 8089:8089
    restart: always
    container_name: spring_app

